### ISSUE TITLE
AttributeError: module 'os' has no attribute 'waitstatus_to_exitcode'

### ISSUE THREAD

**Issue by denis-stepanov** [denis-stepanov/advent#1]
On Raspbian when using PulseAudio TV control:

```
...
Hit: [35] FR_TF1_220205_EVENING2_3
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/home/dns/src/advent/advent-pyenv/lib/python3.7/site-packages/advent/__main__.py", line 85, in run
    if self.tvc.toggleMute() != tv_muted:
  File "/home/dns/src/advent/advent-pyenv/lib/python3.7/site-packages/tv_control/TVControlPulseAudio.py", line 16, in toggleMute
    if os.waitstatus_to_exitcode(ret) == 0:
AttributeError: module 'os' has no attribute 'waitstatus_to_exitcode'
```

Works OK on Fedora.

**Comment by denis-stepanov** [comment]
Actually.. also observed on Fedora.

**Comment by denis-stepanov** [comment]
OK now; resolving.
